-- Deprecated bootstrap file.
--
-- The database schema is now managed through versioned SQL migrations.
-- Apply files from:
--
--   supabase/migrations/
--
-- Current migration:
--
--   supabase/migrations/202607220001_normalize_project_data.sql
