-- Deprecated bootstrap file.
--
-- The database schema is now managed through versioned SQL migrations.
-- Apply files from:
--
--   supabase/migrations/
--
-- Use Supabase CLI rather than this file:
--
--   npm run db:reset
--   npm run db:push:dry-run
--   npm run db:push
